import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://seology.ai'
  const currentDate = new Date().toISOString()

  // Static pages
  const staticPages = [
    {
      url: baseUrl,
      lastModified: currentDate,
      changeFrequency: 'daily' as const,
      priority: 1,
    },
    {
      url: `${baseUrl}/pricing`,
      lastModified: currentDate,
      changeFrequency: 'weekly' as const,
      priority: 0.9,
    },
    {
      url: `${baseUrl}/dashboard`,
      lastModified: currentDate,
      changeFrequency: 'daily' as const,
      priority: 0.8,
    },
  ]

  // Blog posts - all 100+ posts
  const blogPosts = [
    '10-seo-mistakes-killing-shopify-traffic',
    '301-redirects-complete-guide',
    '404-error-optimization-guide',
    'ai-generated-content-seo-guide',
    'ai-seo-agency-complete-guide-2026',
    'ai-seo-optimization-complete-guide-2026',
    'ai-seo-tools-comparison-2025',
    'ai-seo-writer-complete-guide-2026',
    'ai-vs-manual-seo-comparison-2026',
    'alt-text-image-seo-guide',
    'anchor-text-optimization-strategy',
    'automatic-seo-fixes-vs-manual-seo',
    'b2b-seo-tactics-2025',
    'best-ai-seo-software-2026-complete-platform-comparison',
    'best-ai-seo-tools-2026-comparison-guide',
    'bigcommerce-seo-tactics-2025',
    'bounce-rate-reduction-tactics',
    'breadcrumb-navigation-seo',
    'broken-link-building-tactics',
    'canonical-tags-duplicate-content-guide',
    'category-page-optimization-ecommerce',
    'click-through-rate-optimization-serp',
    'competitor-seo-analysis-guide',
    'content-optimization-ai-vs-manual',
    'content-pruning-strategy-guide',
    'conversion-rate-optimization-seo',
    'core-web-vitals-optimization-guide-2025',
    'crawl-budget-optimization-guide',
    'digital-pr-seo-strategy',
    'duplicate-content-solutions-guide',
    'dwell-time-optimization-guide',
    'eat-signals-expertise-authority',
    'ecommerce-seo-strategy-2025',
    'enterprise-seo-strategy-guide',
    'entity-seo-knowledge-graph',
    'event-schema-markup-guide',
    'faceted-navigation-seo-guide',
    'faq-page-optimization-strategy',
    'faq-schema-implementation-guide',
    'featured-snippets-optimization-guide',
    'footer-optimization-seo-guide',
    'google-analytics-4-seo-tracking',
    'google-my-business-optimization',
    'google-ranking-factors-2025',
    'google-search-console-mastery-2025',
    'guest-posting-seo-guide-2025',
    'h1-tag-best-practices-guide',
    'header-tags-optimization-h1-h6',
    'healthcare-seo-compliance-guide',
    'https-migration-seo-guide',
    'image-optimization-seo-guide',
    'internal-linking-strategy-2025',
    'international-seo-hreflang-guide',
    'javascript-rendering-seo',
    'javascript-seo-complete-guide',
    'keyword-research-strategy-2025',
    'knowledge-panel-optimization',
    'landing-page-seo-conversion',
    'lazy-loading-seo-implementation',
    'legal-seo-best-practices-2025',
    'link-building-strategies-2025',
    'link-reclamation-guide-2025',
    'link-velocity-natural-growth',
    'local-seo-automation-guide',
    'log-file-analysis-seo',
    'long-tail-keyword-strategy',
    'magento-seo-optimization-guide',
    'meta-description-best-practices-2025',
    'meta-robots-tags-guide',
    'mobile-first-indexing-checklist-2025',
    'multilingual-seo-strategy',
    'navigation-menu-seo-optimization',
    'news-seo-google-news-optimization',
    'open-graph-tags-social-seo',
    'orphan-page-recovery-strategy',
    'page-titles-vs-h1-tags',
    'pagination-seo-best-practices',
    'ppc-seo-integration-strategy',
    'product-page-seo-ecommerce',
    'real-estate-seo-complete-guide',
    'redirect-chains-audit-fix',
    'review-schema-markup-guide',
    'rich-snippets-complete-guide',
    'robots-txt-configuration-guide',
    'saas-seo-strategy-complete-guide',
    'schema-markup-complete-guide-2025',
    'search-intent-optimization-guide',
    'semantic-seo-nlp-optimization',
    'seo-roi-calculator-guide',
    'seology-reviews-best-ai-seo-automation-2025',
    'shopify-page-speed-optimization',
    'shopify-seo-optimization-guide-2025',
    'site-architecture-seo-best-practices',
    'site-speed-tools-comparison',
    'squarespace-seo-limitations-workarounds',
    'technical-seo-audit-checklist-2025',
    'title-tag-optimization-complete-guide',
    'toxic-backlink-removal-guide',
    'url-structure-best-practices-seo',
    'video-seo-youtube-optimization-2025',
    'voice-search-optimization-2025',
    'webflow-seo-checklist-2025',
    'wix-seo-best-practices-guide',
    'woocommerce-seo-complete-guide',
    'wordpress-seo-automation-best-practices',
    'xml-sitemap-optimization-guide',
    '24-7-ai-seo-automation-complete-guide-2026',
    'ai-seo-shopify-stores-complete-guide-2026',
    'what-is-ai-seo-complete-guide-2026',
  ].map((slug) => ({
    url: `${baseUrl}/blog/${slug}`,
    lastModified: currentDate,
    changeFrequency: 'weekly' as const,
    priority: 0.7,
  }))

  return [...staticPages, ...blogPosts]
}
